version: '3'

services:
  app:
    build: .
    volumes:
      - "./:/app"
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
    command: rails s -b 0.0.0.0
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  cache:
    driver: local
